
cc_library (
    name = "server",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//workspace/common:common"
        , "//workspace/agent:agent"
    ],
    visibility = ["//visibility:public"],
)
