
cc_library (
    name = "server",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//workspace/common:common"
    ],
    visibility = ["//visibility:public"],
    #linkopts = ["-lstdc++_libbacktrace"],
)
