
cc_library (
    name = "com",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    linkopts = [
        "-lzmq"
    ],
#    deps = [
#        "//workspace/common:common"
#    ],
    visibility = ["//visibility:public"],
)




