
cc_library (
    name = "agent",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//workspace/common:common"
        , "//workspace/server:server"
    ],
    visibility = ["//visibility:public"],
)
