# #load("@bazel_skylib//rules:common.bzl", "gtest_suite")

# # Creates a gtest_suite target to run all gtest tests
# test_suite(
#     name = "all_tests",
#     tests = glob(["tests/*.cc"]),
#     deps = [":tool"],
# )
